### PR TITLE
fixed issue where quickumls was ignored in medspacy load method

### PR DESCRIPTION
**Pull request by turbosheep**
Made it so quickumls is not ignored on medspacy.load now that install for quickumls has been improved on windows

### CODE REVIEW

**Comment by jianlins** [comment]
Failed to install unqlite
Building wheels for collected packages: unqlite
  Building wheel for unqlite (setup.py): started
  Building wheel for unqlite (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /private/var/folders/mm/pltwc2yj1jx192t6dzy9zsrr0000gn/T/pip-install-fqp50fxn/unqlite_8ee989ba66064dcc998c69dcc0ed6824/setup.py:11: UserWarning: Cython not installed, using pre-generated C source file.
        warnings.warn('Cython not installed, using pre-generated C source file.')
      /Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

Don't recall how we fixed in current dev version. It might be easier to close this and start a new pull from the latest dev instead? Thoughts? @turbosheep ?

**Comment by burgersmoke** [comment]
I see this in the log.   Have we tried making sure that Cython is installed to prevent this?

`warnings.warn('Cython not installed, using pre-generated C source file.')`

**Comment by jianlins** [comment]
I think this has been fixed since 1.1.5

**Comment by burgersmoke** [comment]
This has not yet been fixed (pulled) into `develop` or `master`.  

This line shows that "medspacy_quickumls" is still commented out, which is the reason for this pull request:

https://github.com/medspacy/medspacy/blob/664128ce0af4481a8312e03ed4fdf7b96e092a73/medspacy/util.py#L26

**Comment by burgersmoke** [comment]
I just made a brief fix to this branch which should allow all tests to succeed.  We'll see if this allows a path forward.

**Pull request merged**
