### PR TITLE
Add custom quickumls args

### PR DESCRIPTION
**Pull request by tnguyen-cohere**

### CODE REVIEW

**Comment by burgersmoke** [comment]
Hi @tnguyen-cohere Sorry I did not follow up with you earlier.  I see that you closed this pull request and deleted the branch.

Out of curiosity, did you find a different workaround or do you still have outstanding needs?

I think I might have some idea of what you were working on here, but I'm thinking that there might be other ways to approach it.  Please let me know where you are so that I might be able to assist.

**Comment by tnguyen-cohere** [comment]
Hi, I was just trying to add more customization to the QuickUMLS in this module. They have things like `overlapping_criteria, threshold, window, similarity_name`. These add a lot of customization. 

The reason I delete the branch is I think this's too hacky but I didn't have time to make it nicer.

**Comment by burgersmoke** [comment]
Got it @tnguyen-cohere .  That makes sense.  When I work with QuickUMLS, I often change some of those exact parameters like `overlapping_criteria` and others.  The loading module we have for `medspacy` is only one way of loading components like this into a pipeline. Just so that we don't need to handle a varying number of arguments for each pipeline component, that for module-level customization (like this one for QuickUMLS) that the component be configured and added to a pipeline outside of the "loading function" we provide in `load()`.

For example, if I wanted to change arguments for the QuickUMLS component, I would use our `load()` as a reference and do something like this:

`from quickumls.spacy_component import SpacyQuickUMLS

# common English pipeline
nlp = spacy.load('en_core_web_sm')

quickumls_component = SpacyQuickUMLS(nlp, 'PATH_TO_QUICKUMLS_DATA', overlapping_criteria = YOUR_ARGUMENT_VALUE_HERE)

nlp.add_pipe(quickumls_component)`

Does that make sense?  Would that be sufficient as a workaround in your case?

**Comment by tnguyen-cohere** [comment]
Thank you for your reply. This surely would be way cleaner.

**Pull request closed without merging**
