### PR TITLE
correct typo in class name of PySBDSentenceSplitter

### PR DESCRIPTION
**Pull request by Mearman**

### CODE REVIEW

**Comment by burgersmoke** [comment]
Just a heads up: We take PRs into `develop` first as a quality check, so I just re-routed the base of this.

I'll peek at this in a bit and make sure that nothing breaks.

**Comment by jianlins** [comment]
Is there anyway, I can edit this pull? 
`from PyRuSH import PyRuSHSentencizer` is not necessary. 
Also, does that means we will need to add pysbd in dependency?
Not sure what causes the test failure. Cannot see the log now.

**Comment by Mearman** [comment]
@jianlins I didn't edit the dependencies. Though I can correct them in the PR if you tell me what it correctly be?

**Comment by jianlins** [comment]
has been fixed in this pull:
https://github.com/medspacy/medspacy/pull/295

**Pull request closed without merging**
