### PR TITLE
Issue 8 add quickumls to pipeline attempt 2

### PR DESCRIPTION
**Pull request by burgersmoke**
Finally resolving Issue #8 to add QuickUMLS to medspacy.   By default, this is only installed and tested for non-Windows systems as Windows currently requires packages to be installed by conda as opposed to setuptools or pip.

An example notebook is now provided showing that UMLS CUIs are extracted from a small sample file.

### CODE REVIEW

**Comment by burgersmoke** [comment]
Please let me know if there are any questions on this at all.

**Comment by burgersmoke** [comment]
As discussed, I added some instructions on Windows.  @abchapman93  is going to try them out.

**Comment by abchapman93** [comment]
Okay, I was able to build this on Windows and use it, it works quite well! I made one additional commit so that it comes before context (otherwise all the QuickUMLS ents won't have context run on them).
I think this is pretty much good to go from my perspective. The new instructions for Windows were really easy to follow and worked. Here are a couple of notes of things that would be useful either now or in the near future:
- Are there instructions, or ideally even a script, for processing the raw UMLS resources that come from NLM and building them in the format needed for QuickUMLS? If we were to add a script for this, it would also be helpful if the script puts it in the standard `resources` location and then we modify the `load()` function to look there for the files so the user doesn't have to always specify the path, maybe just put `quickumls_path="default"`
- As I was going through it, I realized that QuickUMLS sometimes parses entities like "no pneumothorax" with the negation term as part of it, and ConText won't let a modifier modify a span that it is a part of. I should tweak that in ConText
- Once we merge into develop, we should maybe add some more details to the notebook, or integrate it into existing notebooks

Otherwise, I think this is good, and it's really exciting!

**Comment by burgersmoke** [comment]
I'll address the other aspects later, but first the issue of QuickUMLS to be added as a pipeline step before context is crucial.  I just updated this now since I forgot about order importance.  Good eye on this one!

I just looked at your commit and it looks great:

e522725ba38201a7dd99974e9394785aeb106730

**Comment by abchapman93** [comment]
I also don't think these are "must-have" changes to merge into develop, we could add documentation/instructions in develop, so I'm going to mark this code review as done 👍

**Review by abchapman93 — APPROVED** [review]

**Comment by burgersmoke** [comment]
We have a number of things in flight at the moment, so I wanted to make sure another pull request ran clean in CI.

Now that it is, I'll merge this in.

**Pull request merged**
