### PR TITLE
Addressing 2 different issues related to scispacy.  scispacy small mo…

### PR DESCRIPTION
**Pull request by burgersmoke**
…del now requires v0.5.1 so I've updated all notebooks and continuous integration to reflect this.

This fixes the following issues:
#164 
#116

### CODE REVIEW

**Comment by burgersmoke** [comment]
@turbosheep  the CI for this is running now.  Since I actually changed some of the CI (i.e., which scispacy gets installed), if these tests all pass, could you review this change?

Note that I fixed two issues in the same commit and PR.  I usually don't do that, but these were highly related.

**Comment by burgersmoke** [comment]
OK, this passed so the PR can be reviewed anytime.

@jianlins  I will add you as an optional reviewer as well, so that you are at least aware that I've updated a number of CI scripts.

**Review by jianlins — APPROVED** [review]
agree

**Comment by jianlins** [comment]
Oh, didn't notice that's long ago. I think it's been fixed.

**Pull request closed without merging**
